name: MineStaff
main: me.ycxmbo.mineStaff.MineStaff
version: 2.6
api-version: '1.21'
author: 'ycxmbo'
provides: [ "MineStaffAPI" ]
softdepend: [LiteBans, Vulcan, Essentials, PlaceholderAPI]
description: A streamlined Staff Mode plugin for Paper 1.21+

commands:
  staffmode:
    description: Toggle Staff Mode
    usage: /<command>
    aliases: [sm, staff]
    permission: staffmode.toggle
  stafflogin:
    description: Staff must log in before moving or using commands
    usage: /<command> <password>
  staffchat:
    description: Send a message to staff chat
    aliases: [sc]
  report:
    description: Report a player
  infractions:
    description: Manage/view infractions
  rollback:
    description: Open rollback GUI
  cpscheck:
    description: Check clicks-per-second over 10s
  stafflistgui:
    description: Open staff list GUI
  stafflist:
    description: Open staff list GUI (alias)

permissions:
  staffmode.toggle:        { default: op }
  staffmode.teleport:      { default: op }
  staffmode.freeze:        { default: op }
  staffmode.inspect:       { default: op }
  staffmode.vanish:        { default: op }
  staffmode.see:
    description: See vanished staff
    default: op
  staffmode.chat:          { default: op }
  staffmode.alerts:        { default: op }
  staffmode.report:        { default: true }
  staffmode.infractions:   { default: op }
  staffmode.infractions.add: { default: op }
  staffmode.rollback:      { default: op }
  staffmode.silentchest:
    description: Open containers silently in Staff Mode
    default: op
