name: MineStaff
main: me.ycxmbo.mineStaff.MineStaff
version: 1.2
api-version: '1.20'
author: 'ycxmbo'
provides: [ "MineStaffAPI" ]
softdepend: [LiteBans, Vulcan, Essentials, PlaceholderAPI]
description: A streamlined Staff Mode plugin for Paper, Purpur, and Spigot 1.20.x-1.21.x
libraries:
  - net.kyori:adventure-text-minimessage:4.17.0
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.2.0
  - com.mysql:mysql-connector-j:8.4.0
  - redis.clients:jedis:5.1.2
  - org.apache.commons:commons-pool2:2.12.0
  - at.favre.lib:bcrypt:0.10.2

commands:
  staffmode:
    description: Toggle Staff Mode
    usage: /<command>
    aliases: [sm, staff]
    permission: staffmode.toggle
  stafflogin:
    description: Staff must log in before moving or using commands
    usage: /<command> <password>
    aliases: [slogin, stafflog, slog]
  staffchat:
    description: Send a message to staff chat
    aliases: [sc, schat]
  report:
    description: Report a player
    aliases: [rp, reportplayer]
  infractions:
    description: Manage/view infractions
    aliases: [inf, infraction, warns]
  rollback:
    description: Open rollback GUI
    aliases: [rb, invrollback]
  cpscheck:
    description: Check clicks-per-second over 10s
    aliases: [cps]
  stafflistgui:
    description: Open staff list GUI
    aliases: [slg, staffgui]
    permission: staffmode.stafflist.gui
  stafflist:
    description: Show staff list in chat
    usage: /<command>
    aliases: [sl, slist]
    permission: staffmode.stafflist.text
  staffreload:
    description: Reload MineStaff configuration
    usage: /<command>
    aliases: [sr, sreload, minestafreload]
    permission: staffmode.reload
  freeze:
    description: Freeze or unfreeze a player (optionally for seconds)
    usage: /<command> <player> [seconds]
    aliases: [f, ice]
    permission: staffmode.freeze
  inspect:
    description: Open inspector GUI for a player
    usage: /<command> <player>
    aliases: [insp, view]
    permission: staffmode.inspect
  reports:
    description: Open reports GUI
    usage: /<command>
    aliases: [reportsgui, reportlist]
    permission: staffmode.alerts
  staffduty:
    description: Toggle staff duty on/off (enables Staff Mode)
    aliases: [duty, sduty]
    permission: staffmode.duty
  notes:
    description: Manage player notes
    usage: /<command> <player> add <note> | list | remove <index>
    aliases: [note, playernotes]
    permission: staffmode.notes
  profile:
    description: Open player profile GUI
    usage: /<command> <player>
    aliases: [p, playerprofile, pprofile]
    permission: staffmode.inspect
  inspectoffline:
    description: Inspect offline player's inventory/ender chest
    usage: /<command> <player> [ec]
    aliases: [io, offlineinspect, invo]
    permission: staffmode.inspect
  commandspy:
    description: Toggle command spy
    aliases: [cmdspy, cs]
    permission: staffmode.spy
  socialspy:
    description: Toggle social spy for private messages
    aliases: [ss, sspy]
    permission: staffmode.spy
  staff2fa:
    description: Manage staff 2FA (TOTP)
    usage: /<command> enable|confirm <otp>|disable|status
    aliases: [s2fa, 2fa]
    permission: staffmode.login
  evidence:
    description: Attach/list evidence to reports
    usage: /<command> <reportId> add <url>|list
    aliases: [ev, proof]
    permission: staffmode.alerts
  backup:
    description: Request immediate backup from other staff members
    usage: /<command> [reason]
    aliases: [requestbackup, callbackup]
    permission: staffmode.backup
  staffhelp:
    description: Show categorized help for all staff commands
    usage: /<command> [category]
    aliases: [shelp, staffh, sh]
  follow:
    description: Continuously follow a player (teleport to them)
    usage: /<command> <player>
    permission: staffmode.follow
  warn:
    description: Issue and manage player warnings
    usage: /<command> <player> <reason> [severity] [duration] | list/remove/clear/gui
    aliases: [warning, warnings]
    permission: staffmode.warn
  reporthistory:
    description: View report history for a player
    usage: /<command> <player> [filed|against|all|gui]
    aliases: [rhistory, rh, reportlog]
    permission: staffmode.reports.history
  backupdata:
    description: Manage plugin data backups
    usage: /<command> [create|list|restore|auto]
    aliases: [databackup, staffbackup]
    permission: staffmode.backup.manage

permissions:
  staffmode.toggle:        { default: op }
  staffmode.teleport:      { default: op }
  staffmode.freeze:        { default: op }
  staffmode.freeze.use:    { default: op }
  staffmode.freeze.bypass: { default: false }
  staffmode.inspect:       { default: op }
  staffmode.vanish:        { default: op }
  staffmode.see:
    description: See vanished staff
    default: op
  staffmode.chat:          { default: op }
  staffmode.alerts:        { default: op }
  staffmode.report:        { default: true }
  staffmode.infractions:   { default: op }
  staffmode.infractions.add: { default: op }
  staffmode.rollback:      { default: op }
  staffmode.login:         { default: op }
  staffmode.stafflist:
    description: Access any staff list command
    default: op
    children:
      staffmode.stafflist.gui: true
      staffmode.stafflist.text: true
  staffmode.stafflist.gui:
    description: Open the staff list GUI
    default: op
  staffmode.stafflist.text:
    description: View the staff list in chat
    default: op
  staffmode.cpscheck:      { default: op }
  staffmode.reload:        { default: op }
  staffmode.duty:          { default: op }
  staffmode.notes:         { default: op }
  staffmode.profile:       { default: op }
  staffmode.spy:           { default: op }
  staffmode.randomtp:      { default: op }
  staffmode.history:       { default: op }
  staffmode.silentchest:
    description: Open containers silently in Staff Mode
    default: op
  staffmode.backup:
    description: Request backup from other staff members
    default: op
  staffmode.backup.receive:
    description: Receive backup requests from other staff
    default: op
  staffmode.follow:
    description: Follow other players continuously
    default: op
  staffmode.follow.bypass:
    description: Cannot be followed by staff
    default: false
  staffmode.warn:
    description: Issue and manage player warnings
    default: op
  staffmode.reports.history:
    description: View player report history
    default: op
  staffmode.backup.manage:
    description: Create and manage data backups
    default: op
