name: MineStaff
main: me.ycxmbo.mineStaff.MineStaff
version: 1.1
api-version: '1.20'
author: 'ycxmbo'
provides: [ "MineStaffAPI" ]
softdepend: [LiteBans, Vulcan, Essentials, PlaceholderAPI]
description: A streamlined Staff Mode plugin for Paper, Purpur, and Spigot 1.20.x-1.21.x
libraries:
  - net.kyori:adventure-text-minimessage:4.17.0
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.2.0
  - com.mysql:mysql-connector-j:8.4.0
  - redis.clients:jedis:5.1.2
  - org.apache.commons:commons-pool2:2.12.0

commands:
  staffmode:
    description: Toggle Staff Mode
    usage: /<command>
    aliases: [sm, staff]
    permission: staffmode.toggle
  stafflogin:
    description: Staff must log in before moving or using commands
    usage: /<command> <password>
  staffchat:
    description: Send a message to staff chat
    aliases: [sc]
  report:
    description: Report a player
  infractions:
    description: Manage/view infractions
  rollback:
    description: Open rollback GUI
  cpscheck:
    description: Check clicks-per-second over 10s
  stafflistgui:
    description: Open staff list GUI
  stafflist:
    description: Open staff list GUI (alias)
  staffreload:
    description: Reload MineStaff configuration
    usage: /<command>
    permission: staffmode.reload
  freeze:
    description: Freeze or unfreeze a player (optionally for seconds)
    usage: /<command> <player> [seconds]
    permission: staffmode.freeze
  inspect:
    description: Open inspector GUI for a player
    usage: /<command> <player>
    permission: staffmode.inspect
  reports:
    description: Open reports GUI
    usage: /<command>
    permission: staffmode.alerts
  staffduty:
    description: Toggle staff duty on/off (enables Staff Mode)
    aliases: [duty]
    permission: staffmode.duty
  notes:
    description: Manage player notes
    usage: /<command> <player> add <note> | list | remove <index>
    permission: staffmode.notes
  profile:
    description: Open player profile GUI
    usage: /<command> <player>
    permission: staffmode.inspect
  inspectoffline:
    description: Inspect offline player's inventory/ender chest
    usage: /<command> <player> [ec]
    permission: staffmode.inspect
  commandspy:
    description: Toggle command spy
    permission: staffmode.spy
  socialspy:
    description: Toggle social spy for private messages
    permission: staffmode.spy
  staff2fa:
    description: Manage staff 2FA (TOTP)
    usage: /<command> enable|confirm <otp>|disable|status
    permission: staffmode.login
  evidence:
    description: Attach/list evidence to reports
    usage: /<command> <reportId> add <url>|list
    permission: staffmode.alerts

permissions:
  staffmode.toggle:        { default: op }
  staffmode.teleport:      { default: op }
  staffmode.freeze:        { default: op }
  staffmode.freeze.use:    { default: op }
  staffmode.freeze.bypass: { default: false }
  staffmode.inspect:       { default: op }
  staffmode.vanish:        { default: op }
  staffmode.see:
    description: See vanished staff
    default: op
  staffmode.chat:          { default: op }
  staffmode.alerts:        { default: op }
  staffmode.report:        { default: true }
  staffmode.infractions:   { default: op }
  staffmode.infractions.add: { default: op }
  staffmode.rollback:      { default: op }
  staffmode.login:         { default: op }
  staffmode.stafflist:     { default: op }
  staffmode.cpscheck:      { default: op }
  staffmode.reload:        { default: op }
  staffmode.duty:          { default: op }
  staffmode.notes:         { default: op }
  staffmode.profile:       { default: op }
  staffmode.spy:           { default: op }
  staffmode.randomtp:      { default: op }
  staffmode.history:       { default: op }
  staffmode.silentchest:
    description: Open containers silently in Staff Mode
    default: op
