name: MineStaff
main: me.ycxmbo.mineStaff.MineStaff
version: 2.5.0
api-version: '1.21'
author: ycxmbo
softdepend: [LiteBans, Vulcan, Essentials]
description: A streamlined Staff Mode plugin for Paper 1.21+

commands:
  staffmode:
    description: Toggle Staff Mode
    usage: /<command>
    aliases: [sm, staff]
    permission: staffmode.toggle
  stafflogin:
    description: Staff login and password management
    permission: staffmode.login
  stafflist:
    description: List staff currently in Staff Mode
    permission: staffmode.list
  staffreload:
    description: Reload MineStaff configuration
    permission: staffmode.reload
  staffchat:
    description: Toggle or send a staff chat message
    permission: staffmode.chat
    aliases: [sc]
  inspect:
    description: Open an inspector GUI for a player
    permission: staffmode.inspect
  freeze:
    description: Freeze or unfreeze a player
    permission: staffmode.freeze
  cpscheck:
    description: Start a CPS test for a player
    permission: staffmode.cpscheck

permissions:
  staffmode.toggle:
    description: Toggle Staff Mode
    default: op
  staffmode.login:
    description: Use /stafflogin
    default: op
  staffmode.list:
    description: Use /stafflist
    default: op
  staffmode.reload:
    description: Reload plugin config
    default: op
  staffmode.chat:
    description: Use staff chat
    default: op
  staffmode.inspect:
    description: Inspect players
    default: op
  staffmode.freeze:
    description: Freeze players
    default: op
  staffmode.cpscheck:
    description: Use CPS checker
    default: op
  staffmode.vanish:
    description: Toggle vanish
    default: op
  staffmode.teleport:
    description: Use teleport tool
    default: op
  staffmode.see:
    description: See vanished staff
    default: op
  staffmode.alerts:
    description: Receive staff alerts
    default: op
